### ISSUE TITLE
Question for inference speed

### ISSUE THREAD

**Issue by an-yongqi** [yxli2123/LoSparse#1]
@yxli2123  Very interesting work! I would like to know if splitting the original weight matrix into low rank and sparse matrices can achieve real inference acceleration like structured pruning? It seems to me that Y=(XU)V+XS is possible to achieve acceleration, and I'm curious what the specific ground acceleration looks like?

**Comment by yxli2123** [comment]
Thanks for your interest. Our method mainly focus on compression: we try to reduce the size of the model. As for the acceleration, unfortunately, we are unable to accelerate the inference significantly due to the overhead. 

This overhead happens after the multiplication of the structured sparse matrix S and the input X. Since the columns in S has been pruned, the output dimension XS no longer matches the original output Y. We need to create a new table that records the zero columns in S and insert zeros into the output XS so that it matches the dimension of Y. Because of this overhead, the acceleration is only x1.5 faster if tested on CPU. It will be less than x1.5 if tested on GPU

**Comment by an-yongqi** [comment]
Thanks for your reply. BTW, I really love your logo 😄.
